<?php

/**
 * @file
 * Customize the presentation of CAPTCHA controls.
 */

/**
 * Implements hook_form_FORM_ID_alter().
 */
function nys_captcha_form_nys_messaging_senator_contact_form_alter(&$form, &$form_state) {
  // Remove captcha from Senator contact form (node/%nid/contact) if user has
  // NOT submitted it this session already.
  if (array_key_exists('captcha', $form['actions']) && (empty($_SESSION) || !$_SESSION['nys_captcha_senator_contact_submitted'])) {
    unset($form['actions']['captcha']);
  }
}

/**
 * Implements hook_form_alter().
 */
function nys_captcha_form_alter(&$form, &$form_state, $form_id) {
  if (function_exists('captcha_get_form_id_setting')) {
    // Is this form supposed to have a CAPTCHA?  If so, add a custom class.
    $has_captcha = captcha_get_form_id_setting($form_id);
    if ($has_captcha) {
      $form['#attributes']['class'][] = 'has-nys-captcha';
    }
  }
}
